import "./globals.css";
import { Inter } from "next/font/google";
import Headers from "./Headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "그린브릭스컴퍼니",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Headers />
        {children}
      </body>
    </html>
  );
}
